name: Install Fast DDS
description: Install and setup Fast DDS for linking and building application in Windows
inputs:
  cmake_build_type:
    description: 'Specifies the build type on single-configuration generators'
    required: true
    default: 'Release'
  fastdds_branch:
    description: 'Branch or tag of eProsima/Fast-DDS repository (https://github.com/eProsima/Fast-DDS)'
    required: true
    default: '2.11.x'
runs:
  using: composite
  steps:
  - run: >
      git clone https://github.com/eProsima/Fast-DDS.git --branch ${{ inputs.fastdds_branch }};
      cmake -DTHIRDPARTY=ON -DSECURITY=ON -DCOMPILE_EXAMPLES=OFF -DEPROSIMA_BUILD_TESTS=OFF `
        -DINTERNAL_DEBUG=ON -Ax64 -T host=x64 -B build\fastdds Fast-DDS;
      cmake --build build\fastdds --config ${{ inputs.cmake_build_type }} --target install
    shell: pwsh
