const long UNDEFINED = 0x10000000;
const long SAMPLE_LOST = 0x10000001;
const long TOPIC_MISMATCH_TYPE = 0x10000002;
const long TOPIC_MISMATCH_QOS = 0x10000003;

enum Kind {
   Info,
   Warning,
   Error
};

struct LogEntry {
   @key long event;
   Kind kind;
   string category;
   string message;
   string timestamp;
};
