// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file enum_struct.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "enum_struct.h"

#if FASTCDR_VERSION_MAJOR == 1

#include "enum_structTypeObject.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

namespace helper { namespace internal {

enum class Size {
    UInt8,
    UInt16,
    UInt32,
    UInt64,
};

constexpr Size get_size(int s) {
    return (s <= 8 ) ? Size::UInt8:
           (s <= 16) ? Size::UInt16:
           (s <= 32) ? Size::UInt32: Size::UInt64;
}

template<Size s>
struct FindTypeH;

template<>
struct FindTypeH<Size::UInt8> {
    using type = std::uint8_t;
};

template<>
struct FindTypeH<Size::UInt16> {
    using type = std::uint16_t;
};

template<>
struct FindTypeH<Size::UInt32> {
    using type = std::uint32_t;
};

template<>
struct FindTypeH<Size::UInt64> {
    using type = std::uint64_t;
};
}

template<int S>
struct FindType {
    using type = typename internal::FindTypeH<internal::get_size(S)>::type;
};
}

#define enum_struct_max_cdr_typesize 12ULL;





enum_struct::enum_struct()
{
    // unsigned long m_index
    m_index = 0;
    // ColorEnum m_enum_value
    m_enum_value = ::RED;

    // Just to register all known types
    registerenum_structTypes();
}

enum_struct::~enum_struct()
{
}

enum_struct::enum_struct(
        const enum_struct& x)
{
    m_index = x.m_index;


    m_enum_value = x.m_enum_value;

}

enum_struct::enum_struct(
        enum_struct&& x) noexcept
{
    m_index = x.m_index;


    m_enum_value = x.m_enum_value;

}

enum_struct& enum_struct::operator =(
        const enum_struct& x)
{
    m_index = x.m_index;


    m_enum_value = x.m_enum_value;

    return *this;
}

enum_struct& enum_struct::operator =(
        enum_struct&& x) noexcept
{
    m_index = x.m_index;


    m_enum_value = x.m_enum_value;

    return *this;
}

bool enum_struct::operator ==(
        const enum_struct& x) const
{
    return (m_index == x.m_index &&
           m_enum_value == x.m_enum_value);
}

bool enum_struct::operator !=(
        const enum_struct& x) const
{
    return !(*this == x);
}

size_t enum_struct::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return enum_struct_max_cdr_typesize;
}

size_t enum_struct::getCdrSerializedSize(
        const enum_struct& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    return current_alignment - initial_alignment;
}


void enum_struct::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{
    scdr << m_index;

    scdr << (uint32_t)m_enum_value;

}

void enum_struct::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{
    dcdr >> m_index;



    {
        uint32_t enum_value = 0;
        dcdr >> enum_value;
        m_enum_value = (ColorEnum)enum_value;
    }


}


bool enum_struct::isKeyDefined()
{
    return false;
}

void enum_struct::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}

/*!
 * @brief This function sets a value in member index
 * @param _index New value for member index
 */
void enum_struct::index(
        uint32_t _index)
{
    m_index = _index;
}

/*!
 * @brief This function returns the value of member index
 * @return Value of member index
 */
uint32_t enum_struct::index() const
{
    return m_index;
}

/*!
 * @brief This function returns a reference to member index
 * @return Reference to member index
 */
uint32_t& enum_struct::index()
{
    return m_index;
}


/*!
 * @brief This function sets a value in member enum_value
 * @param _enum_value New value for member enum_value
 */
void enum_struct::enum_value(
        ColorEnum _enum_value)
{
    m_enum_value = _enum_value;
}

/*!
 * @brief This function returns the value of member enum_value
 * @return Value of member enum_value
 */
ColorEnum enum_struct::enum_value() const
{
    return m_enum_value;
}

/*!
 * @brief This function returns a reference to member enum_value
 * @return Reference to member enum_value
 */
ColorEnum& enum_struct::enum_value()
{
    return m_enum_value;
}




#endif // FASTCDR_VERSION_MAJOR == 1
